WIP: Fix/naming issue, next regimen is 1.1.2
AllenInstitute/mtrain_regimens pull request #61
Opened 2019-03-02 00:19 UTC by jeromelecoq

1/ This is make stash and GitHub more in par
2/ Correcting naming issue

2019-03-07 19:26 UTC, nicain requested changes

2019-03-07 19:26 UTC, nicain commented on regimen.yml
> +name: VisualBehavior_Task1A_v1.1.1
This regimen name is already deployed.

2019-03-08 20:17 UTC, nicain commented
This branch is currently 2 commits past the tagged 1.1.1 branch that was deployed (64d848e4982e3edc5384b2699f1ae2ced1ac42b4). My suggestion is to use this branch, with an additional commit, to define regimen 1.1.2. @jeromelecoq does this sound good?

2019-03-08 20:19 UTC, jeromelecoq commented
ok

2019-03-15 20:13 UTC, nicain commented
@jeromelecoq I put some testing infrastructure in-place, so that the current problem with this PR causes a blocker to merging.

You can read more about the infrastructure here:
https://github.com/AllenInstitute/mtrain_regimens/issues/67

This PR will not be mergable until, in this case, the regimen-name-already-in-use problem is fixed.  To see that this is the problem, go to "details" and click down through the build report until you hit the error report: http://bamboo.corp.alleninstitute.org/browse/VB-MB3-JOB1-1/test/case/169970754.  A new commit on the branch that is the source of the PR can fix the issues; the continuous-integration will be re-run for every commit.

2019-03-15 20:21 UTC, closed without merging